server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal_db
    username: root
    password: your_password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddlAuto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

email:
  sender: YOUR_EMAIL
  password: YOUR_PASSWORD

jwt:
  secret: 2a$10$VkppiB//npG.ooITo9tjv.YAyeTomsB9PtWOhWpIx4LyO26boOe22
  time: 86400000